[package]
name = "auction2025"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
rand = "0.8.5"
tokio = { version = "1.42.0", features = ["full"]}
csv = "1.3.0"
tokio-stream = "0.1.17"




